server:
  servlet:
    context-path: /
  port: 0

spring:
  application:
    name: service-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: pulsarsystemteam@gmail.com
    password: vzqbxnxkbfcnmysp
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
            required: true
          from: pulsarsystemteam@gmail.com
        auth: true
    default-encoding: UTF-8
    test-connection: false
  kafka:
    bootstrap-servers: localhost:9092

kafka:
  enable: false

mail:
  from:
    name: Pulsar
