server:
  servlet:
    context-path: /
  port: 0

spring:
  application:
    name: service-mail
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
            required: true
          from: ${MAIL_USERNAME}
        auth: true
    default-encoding: UTF-8
    test-connection: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}

kafka:
  enable: true

mail:
  from:
    name: Pulsar
