server:
  servlet:
    context-path: /
  port: 0

spring:
  application:
    name: service-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_MAIL}
    password: ${PASSWORD_MAIL}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
            required: true
          from: ${USERNAME_MAIL}
        auth: true
    default-encoding: UTF-8
    test-connection: false
  kafka:
    bootstrap-servers: localhost:9092

mail:
  from:
    name: Pulsar
